### ISSUE TITLE
CocoaPods 1.0 Build Error 'Swinject/_SwinjectStoryboardBase.h' file not found

### ISSUE THREAD

**Issue by bclymer** [Swinject/Swinject#96] opened 2016-05-12 14:04 UTC
After upgrading to CocoaPods 1.0.0 this morning, I've getting a compile time error with Swinject.

```
/Users/myuser/Documents/Github/myrepo/Pods/Swinject/Sources/Swinject.h:23:9: 'Swinject/_SwinjectStoryboardBase.h' file not found
```

I found [this issue](https://github.com/Swinject/Swinject/issues/67) but my target is set to iOS 9.3, so I didn't think it was relevant.

Everything was working on CocoaPods 0.39.0

**Comment by bclymer** [comment] 2016-05-12 14:39
Issues are being reported on the main CocoaPods repo. Will follow those and update.
https://github.com/CocoaPods/CocoaPods/issues/4950
https://github.com/CocoaPods/CocoaPods/issues/5283

**Comment by yoichitgy** [comment] 2016-05-12 14:45
@bclymer Thank you for checking the CocoaPods issues😃 Since my environment didn't reproduce the issue with CocoaPods v1.0.0, I didn't know where I should start to investigate the problem.

I keep this issue open for other users experience the issue.

**Comment by bclymer** [comment] 2016-05-12 15:49
Well the plot **thickens**.

I was going to just avoid Xcode because it's awful and use [gym](https://github.com/fastlane/fastlane/tree/master/gym) instead. There was a [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) error instead of this error. After removing the CocoaLumberjack dependency, I was able to build the entire product.

Did a full clean + derived data wipe, went back into Xcode, and it still fails to build with the error in this issue, despite gym successfully building and archiving.

I realized gym would have build for arm instead of x86, so I switched Xcode to "Generic iOS Device", I got 18 different errors for many pods building for arm debug. I then tried arm archive in Xcode, it worked. So I assume it's something about building for debug.

After all of that, if I go back to just wanting to run on the Simulator, I get the same error in this issue again. 

I might go back to 0.39.0 for now. See if other people around the web have problems like this.

**Comment by paulz** [comment] 2016-05-13 19:27
Same issue here: after upgrading to cocoapods 1.0.0, Xcode can't build `Swinject` module
```
...<module-includes>:1:9: In file included from <module-includes>:1:

...Pods/Target Support Files/Swinject/Swinject-umbrella.h:4:9: In file included from .../Build/Products/Debug-iphonesimulator/Swinject/Swinject.framework/Headers/Swinject-umbrella.h:4:

...Pods/Swinject/Sources/Swinject.h:23:9: 'Swinject/_SwinjectStoryboardBase.h' file not found

Could not build Objective-C module 'Swinject'
```

**Comment by paulz** [comment] 2016-05-13 19:35
Renaming `_SwinjectStoryboardBase.h` to `SwinjectStoryboardBase.h` helped to resolve the file not found error, but now we have another
```
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/Swinject-Swift.h"
        ^
.../Build/Products/Debug-iphonesimulator/Swinject/Swinject.framework/Headers/Swinject-Swift.h:98:9: error: 'Swinject/Swinject.h' file not found
#import <Swinject/Swinject.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Swinject'
```

**Comment by yoichitgy** [comment] 2016-05-14 00:04
@paulz thanks for sharing your experience. Did you use `gym` like @bclymer used? I need to know environment to reproduce the issue.

**Comment by yoichitgy** [comment] 2016-05-18 23:56
Please anyone feel free to write here to share your environment to reproduce the issue.

**Comment by koogle** [comment] 2016-05-23 11:18
Can reproduce. Got the same error after updating to CocoaPods 1.0.0. Using just Xcode and CocoaPods but we are building for `tvOS 9.0`.

**Comment by yoichitgy** [comment] 2016-05-23 14:33
@koogle thank you for sharing your experience. Could you show me your `Podfile` or simplified one with your private things removed? I'll try investigating the issue again.

**Comment by koogle** [comment] 2016-05-23 14:36
This is the content of my Podfile:
```
platform :tvos, '9.0'
use_frameworks!
xcodeproj './projectname'

target 'projectname' do
  pod 'TVOSToast', '0.5'
  pod 'ObjectMapper', '1.2.0'
  pod 'AlamofireObjectMapper', '3.0.0'
  pod 'Swinject', '1.1.1'
  pod 'Charts', '2.2.4'
  pod 'JKBCrypt', '0.1.0'
  pod 'OHHTTPStubs', '5.0.0'
  pod 'OHHTTPStubs/Swift', '5.0.0'
end
```

**Comment by yoichitgy** [comment] 2016-05-23 14:40
Thanks @koogle😃 I'll take time to investigate the issue.

**Comment by cooler333** [comment] 2016-05-26 07:19
clean project -> delete derived data -> clean project again -> run

**Comment by yoichitgy** [comment] 2016-05-26 10:14
Thanks @cooler333!
@koogle could you try deleting derived data?

**Comment by yoichitgy** [comment] 2016-06-04 01:06
Thanks @jlyonsmith😃 It looks cleaning the things can be a workaround for the issue in most of cases except a few cases like @bclymer has.

I'll keep watching the Issues on CocoaPods.

**Comment by yoichitgy** [comment] 2016-08-19 09:20
I'm going to close this issue because it looks cleansing and deleting derived data work.

**Closed by yoichitgy** 2016-08-19 09:20 UTC
