### ISSUE TITLE
Swinject Podfile for ios/tvos and osx

### ISSUE THREAD

**Issue by phonaddicts** [Swinject/Swinject#68] opened 2016-03-03 11:57 UTC
When using Swinject with cocoapods targeting iOS/tvOS as well OSX, the compiler seems not to be able to find the correct header file in "Swinject.h"

changing the line 
#import <Swinject/_SwinjectStoryboardBase.h>
to
#import "_SwinjectStoryboardBase.h"

resolves the issue. Sorry for me not having seen that issue before.

**Comment by yoichitgy** [comment] 2016-03-03 12:15
Would you tell me more about the problem? Are you using Swinject in Objective-C?

**Comment by phonaddicts** [comment] 2016-03-03 12:22
Hi Yoichi. I am actually using it with swift. I started in Xcode with a new iOS project and adding an OSX target. Afterwards closed the project and did the usual pod init, Podfile editing, pod install, pod update ceremony. After that opened the workspace and tried to compile iOS and OSX. When compiling the iOS target, the compiler complaint that <Cocoa/Cocoa.h> could not be found in _SwinjectStoryboardBase.h, so obviously the wrong variant is found by using #import <Swinject/_SwinjectStoryboardBase.h>.

**Comment by yoichitgy** [comment] 2016-03-03 12:44
Thank you for the answer.  Did you mean a file contained only `#import` and it should be fixed to `#import _SwinjectStoryboardBase.h`. Which file contains only `#import`?

**Comment by phonaddicts** [comment] 2016-03-03 12:48
Seems I failed pasting the path, so it should read changing (line 23 in Swinject.h) from
#import <Swinject/_SwinjectStoryboardBase.h>
to 
#import "_SwinjectStoryboardBase.h"
fixed the issue for me.

**Comment by yoichitgy** [comment] 2016-03-03 12:52
I think I experienced a similar issue and fixed already. Would you tell me which version you installed?

**Comment by phonaddicts** [comment] 2016-03-03 12:53
I am using 1.1.0

**Comment by yoichitgy** [comment] 2016-03-03 13:00
You might need to write your `Podfile` like this:

```ruby
target :ios do
    platform :ios, '8.0'
end

target :osx do
    platform :osx, '10.10'
end
```

More info here: https://github.com/CocoaPods/CocoaPods/issues/2043

Does your `Podfile` has that kind of switch between iOS and osx?

**Comment by phonaddicts** [comment] 2016-03-03 13:08
Actually I am using a slightly different syntax:
```
target 'iosApp' do
  platform :ios, '8.4'
  pod 'Swinject', '~> 1.1.0'
end

target 'macApp' do
  platform :osx, '10.10'
  pod 'Swinject', '~> 1.1.0'
end
```

I tried your syntax, but that gave me an error:

> Unable to find a target named `ios`

**Comment by yoichitgy** [comment] 2016-03-03 13:31
I couldn't reproduce the issue but got `pod install` command warning "[!] [Xcodeproj] Generated duplicate UUIDs:"

Although I couldn't reproduce the problem, but I think what you see is a problem appearing only when a project contains both iOS and OSX targets and Swinject is installed by CocoaPods. If only a target is contained or Carthage is used, the problem is not reproducible.

If we modify `#import <Swinject/_SwinjectStoryboardBase.h>` to `#import "_SwinjectStoryboardBase.h"`, we will have a problem with Carthage.

So I would like to provide the workaround you shared for the case targeting both iOS and OSX, and installing with CocoaPods.

The workaround is changing

`#import <Swinject/_SwinjectStoryboardBase.h>`

in Swinject.h to

`#import "_SwinjectStoryboardBase.h"`

by each user.

Do you think the workaround is acceptable? Thank you for sharing the problem you experienced with the combination.

**Comment by phonaddicts** [comment] 2016-03-03 13:35
I think it is acceptable, sure.
Do you prefer Carthage over Cocoapods, would you recommend moving to Carthage for future projects?

**Comment by yoichitgy** [comment] 2016-03-03 13:38
Both Carthage and CocoaPods have their advantages/disadvantages depending on projects. If I have a problem with CocoaPods, I use Carthage in the project, and vice versa.

**Closed** 2016-03-04 09:10 UTC
Labels: bug, question, wontfix
