### ISSUE TITLE
Resolving non-class protocols in .weak object scope on Xcode 10

### ISSUE THREAD

**Issue by m3g0byt3** [Swinject/Swinject#366] opened 2018-08-20 11:44 UTC
Hello guys.
First of all - thank you for the great framework, it makes DI on Swift smooth and enjoyable.
 
Recently I've noticed a strange bug (or a feature perhaps 🤔) with a `.weak` object scope while working on my project in Xcode 10 and spent around a hour to figure it out.

My environment:
- Your Xcode version: `10.0 beta 6`
- Your Swinject version: `2.4.1` (latest from Pods)
- The steps to reproduce the issue:
  -  Use Xcode 10
  -  Register reference-semantic type in a container with `.weak` object scope for **non-class** plain Swift protocol
  -  Try to resolve it a few times, creating strong reference to a resolved instance each time
  -  A new instance will be created during each resolution cycle

I've created [sample project ](https://github.com/m3g0byt3/swinject-weak-object-scope) to demonstrate this issue, please take a look at `ContainerSpec` test, it's self explanatory.

This issue arises only in Xcode 10 beta 6 (although I'm unable to test previous betas), with Swift 4.2 and 4.1.2 `SWIFT_VERSION`.

This issue is never arises when using the `.container` object scope, with other conditions the same (non-class plain Swift protocol as a Service and reference-semantic type as a Component).

I've quickly looked at the Swinject source code - the suspicious place is  [Container.swift:300](https://github.com/Swinject/Swinject/blob/master/Sources/Container.swift), where are optional casting and binding occur.
It's looks like the Swift (version 4.2?) complier cannot cast an instance of reference-semantic type to   non-class plain Swift protocol, when the instance is inside following nested optional:
```
▿ Optional<Any>
  ▿ some : Optional<AnyObject>
    - some : <SingletonClass: 0x600000013290>
```

I've also implemented quick and dirty fix for the issue - [9da3ddf](https://github.com/m3g0byt3/Swinject/commit/9da3ddf528164fedffb614fb356908c1ccb3680f)
This is pure experimental and untested and, in my opinion, double binding and casting looks ugly.

Actually, I'm unsure is it worth fixing - because using non-class protocol with reference-semantic type is a bit non-sense (although it can be used in certain cases, like mine), but at least docs should be updated if the issue persists on release Xcode build.

**Comment by jakubvano** [comment] 2018-09-18 10:29
Thanks for investigating this 👍 It is related to the broader issue, caused by different behavior of Swift 4.2 when unwrapping `nil` values as `Any`, see description in #371 .

Resolved by #371

**Closed by jakubvano** 2018-09-18 10:29 UTC
