### ISSUE TITLE
container.registerForStoryboard subclass of AVPlayerViewController fails

### ISSUE THREAD

**Issue by jondwillis** [Swinject/Swinject#18] opened 2015-10-19 18:57 UTC
On tvOS, I have several view controllers that I inject into. This is from latest xcode7.1 branch.

```
        container.registerForStoryboard(MainViewController.self) { r, c in
            c.app = r.resolve(App.self)
        }
        
        container.registerForStoryboard(VideoViewController.self) { r, c in
            c.app = r.resolve(App.self)
            c.video = r.resolve(VideoService.self)
        }
        
        container.registerForStoryboard(MetadataViewController.self) { r, c in
            c.app = r.resolve(App.self)
        }
        
        container.registerForStoryboard(ChannelsGuideViewController.self) { r, c in
            c.app = r.resolve(App.self)
        } 
```
and then
```
        let storyboard = SwinjectStoryboard.create(name: "Main", bundle: bundle, container: container)
        window.rootViewController = storyboard.instantiateInitialViewController()
```

`VideoViewController`, `MetadataViewcontroller`, and `ChannelsGuideViewController` are all embedded in `MainViewController`. Injection fails on `VideoViewController` if it subclasses from `AVPlayerViewController`. Inside of     `internal func runInitCompleted<C: Controller>(controllerType: C.Type, controller: C, name: String? = nil)` I can see that normally, `controllerType` is set, however it is nil for the subclass of `VideoViewController`.

This seems related to https://github.com/Swinject/Swinject/issues/10

**Comment by yoichitgy** [comment] 2015-10-20 08:49
What does "injection fails" mean? Did the container return nil or crash? Can you provide a small simplified project to reproduce the issue?

**Comment by yoichitgy** [comment] 2015-10-24 11:19
I'll investigate this issue after Nimble issue 208 is resolved because it's easier to write a unit test for tvOS after the issue is fixed.

**Comment by yoichitgy** [comment] 2015-10-27 10:56
Reproduced by changing the super class of `AnimalViewController` to `AVPlayerViewController` defined in the unit tests.

Only tvOS target reproduces the issue. `controllerType` in `runInitCompleted` method does not resolved to `AnimalViewController` type if the super class is `AVPlayerViewController`. It looks `dynamicType` property does not return the actual type at runtime.

**Comment by yoichitgy** [comment] 2015-10-29 08:52
tvOS with Xcode 7.2 beta 1 still has the issue.

**Comment by yoichitgy** [comment] 2015-11-01 04:16
![screenshot](https://cloud.githubusercontent.com/assets/965994/10867249/a0eb0d28-809a-11e5-87db-1876d3d8236c.png)

**Comment by yoichitgy** [comment] 2015-11-01 04:20
![screenshot](https://cloud.githubusercontent.com/assets/965994/10867260/44dc1e54-809b-11e5-92f0-b6f8d41350d5.png)

**Comment by yoichitgy** [comment] 2015-11-01 04:58
Merged. Version 0.4.1 will include the fix. Thanks, @jondwillis, for submitting the issue.

**Closed by yoichitgy** 2015-11-01 04:58 UTC
Labels: bug
