### ISSUE TITLE
Does not compile out of the box

### ISSUE THREAD

**Issue by rcfrias** [Swinject/Swinject#189] opened 2016-11-14 16:05 UTC
I downloaded the code and try to use the playground, and it cant find the Swinject library, there is an error on the import.

**Comment by yoichitgy** [comment] 2016-11-14 16:15
Thank you for notifying the problem. As you see, this issue is a duplicate of #130. I'm going to close this issue.

I'll try a good resolution for the problem. I understand downloading a zip file to run the playground is easy for new users.

**Closed by yoichitgy** 2016-11-14 16:15 UTC
Labels: duplicate
