### ISSUE TITLE
3 members circular dependency issue

### ISSUE THREAD

**Issue by alexisbronchart** [Swinject/Swinject#302] opened 2017-10-25 09:27 UTC
I want to make an object graph with classes A, B and C.
A has a strong ref to B, B has a strong ref to C and C has a weak ref to A

I'm trying to make my assembly like this:
```
public func assemble(container: Container) {
    container.register(A.self) { _ in
        let b = container.resolve(B.self)!
        return A(b: b)
    }
    .inObjectScope(.weak)
    
    container.register(B.self) { _ in
        let c = container.resolve(C.self)!
        return B(c: c)
    }
    .inObjectScope(.weak)
    
    container.register(C.self) { _ in
        return C()
    }
    .initCompleted { r, c in
        let a = r.resolve(A.self)!
        c.a = a
    }
    .inObjectScope(.weak)
}
```

When I resolve A, the object graph is properly created BUT the weak ref from the C instance to the A instance is nil. 
I understand that since I'm using the weak scope, the A instance resolved in initCompleted is immediately lost since the first call to resolve A hasn't returned yet (At least that's my guess, am I right or could this actually be a bug?).
How could I make this work? (Preferably without using optional types)

**Comment by alexisbronchart** [comment] 2017-10-25 20:32
I ended up doing it like this:
```
public func assemble(container: Container) {
    container.register(A.self) { _ in
        let b = container.resolve(B.self)!
        return A(b: b)
    }
    .initCompleted { r, a in
        let c = r.resolve(C.self)!
        c.a = a
    }
    .inObjectScope(.weak)
    
    container.register(B.self) { _ in
        let c = container.resolve(C.self)!
        return B(c: c)
    }
    .inObjectScope(.weak)
    
    container.register(C.self) { _ in
        return C()
    }
    .inObjectScope(.weak)
}
```

Any comment?

**Comment by jakubvano** [comment] 2018-02-07 11:11
Hello @alexisbronchart,
This looks like a bug indeed - as you mentioned, instance of `A` assigned to the `C` is immediately discarded, as no strong references exist to it.
I guess the expected behaviour would be such that even `.weak` object scope instances do not discard during graph resolution.
Any help fixing this would be welcome 😉

**Closed** 2018-02-16 11:32 UTC
Labels: bug, help wanted
