### ISSUE TITLE
Parent-child with arguments

### ISSUE THREAD

**Issue by zefender** [Swinject/Swinject#208] opened 2016-12-19 19:05 UTC
I have two parent-child related types.
```swift
container.register(ChildType.self) { resolver, param1 in
            ChildTypeImpl(param1: param1)
            }.initCompleted { resolver, child in
                child.parent = resolver.resolve(ParentType.self, argument: param2) // haven't param2
}
        
container.register(ParentType.self) { resolver, param2 in
            ParentTypeImpl(child: resolver.resolve(ChildType.self, argument: param1), param2) // haven't param 1
 }
```

Each of them have it's params, example above.
How to resolve it? 
I tried to add param1 to ParentType's registration, but how to access to it in the 'initCompleted' closure?

Thank you!

**Comment by jakubvano** [comment] 2016-12-20 08:35
Hi @zefender,
Unfortunatelly, currently there is no way of accessing arguments inside `initCompleted`closures, which makes circular dependencies with arguments tricky. I would suggest  to structure your app to avoid such dependencies, but if inevitable something like this could be used:

```swift
container.register(Parent.self) { (r, param1: String, param2: String) in
    let child = Child(param1: param1)
    let parent = Parent(child: child, param2: param2)
    child.parent = parent
    return parent
}
container.register(Child.self) { (r, param1: String, param2: String) in
    r.resolve(Parent.self, arguments: param1, param2)!.child
}
```
Pattern above is neither pretty nor very extensible, but AFAIK there is no better alternative to circular dependencies with arguments atm.

Hope this helps 😉

**Comment by zefender** [comment] 2016-12-20 12:15
@jakubvano Thank you for quick reply! In my case child is private member by design. My solution is to use another objects to link this objects. It is actually Assembly types (from VIPER) where I use DI. There are more classes, but more flexibility.

**Comment by jakubvano** [comment] 2016-12-20 12:28
@zefender Using other objects to work around this would probably be my approach as well.
I'm glad you've found a satisfying solution 👍

**Comment by yoichitgy** [comment] 2017-01-06 12:47
I'm closing this issue because a satisfying solution looked found. @zefender, please feel free to reopen this issue if the issue is not actually resolved.

**Closed by yoichitgy** 2017-01-06 12:47 UTC
Labels: question
