### ISSUE TITLE
"Resolution failed" error, when it did not fail

### ISSUE THREAD

**Issue by J7mbo** [Swinject/Swinject#328] opened 2018-03-04 22:05 UTC
Even though resolution seems to have succeeded (the object exists, and I can use it!!), I get an error in console.

```
    container.register(HomeViewController.self) { _ in
            let vc = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
            print("-=-")
            print(vc)
            return vc
        }

    container.resolve(HomeViewController.self)
```

The error:
--

> Swinject: Resolution failed. Expected registration:
	{ Service: UIViewController, Storyboard: PalmaGo.HomeViewController, Factory: (Resolver, UIViewController) -> UIViewController }
Available registrations:
> -=-
> <MyApp.HomeViewController: 0x7f823a006d90>

Looks like a bug?

---

I've also tried with **SwinjectStoryboard**:

```
container.register(HomeViewController.self) { r in
        let vc = SwinjectStoryboard.create(name: "Main", bundle: nil, container: r).instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
        return vc
    }
```

Same error.

**Comment by jakubvano** [comment] 2018-03-05 09:10
It is a known issue when using SwinjectStoryboard - basically SwinjectStoryboard is trying to inject dependencies to each (event not directly) instantiated `UIViewController`, which ofter results into (benign) resolution failure. For more info see #213.

Closing this, as it is a duplicate of #213

**Closed by jakubvano** 2018-03-05 09:10 UTC

**Comment by J7mbo** [comment] 2018-03-05 09:12
Thanks for the swift response!

This also happened *without* the storyboard lib, in case that wasn’t clear. I’ll check out the other post, thanks 😊

**Comment by jakubvano** [comment] 2018-03-05 09:30
🤔 If this happened without SwinjectStoryboard, than something really weird is going on.

However, based on error message I suspect that even in the first case SwinjectStoryboard is the culprit - once you initialise it, it can come into play even when you are using "normal" `UIStoryboard.instantiateViewController`

**Comment by J7mbo** [comment] 2018-03-05 09:41
The only reason I’m using SwinjectStoryboard is because I couldn’t figure out a different way to initialise a default UIViewController programmatically with swinject. I think I opened an issue about that as my controller had an initialiser as well, which I since removed to get to this point.

So for me it seems like a lose-lose, I either can instantiate a default view controller, *or* set up other view controllers for injection (without error), so I’m not sure what to do.

**Comment by jakubvano** [comment] 2018-03-05 10:07
I commented on your other issues, hopefully it will help ;)

Basically you have 2 options:
1. **Use SwinjectStoryboard**: it is easier to set up, you can disable failure logging with `Container.loggingFunction = nil`. On the other hand you lose some control over your navigation flow, and may run into scaling issues (Personally, I only use it for small projects)

2. **Wire everything yourself** - you cannot rely on storyboard segues, so you will have to write the routing code (You can still use storyboards / xibs for creating individual view controllers though). As far as swinject goes, you can treat `UIViewController` as any other objects - basically what you have done in your first case.

**Comment by ZZHHAANNGG** [comment] 2018-07-26 16:13
I have the same issue, even if I do not use SwinjectStoryboard. Please check the screenshot.

![image](https://user-images.githubusercontent.com/12008247/43274474-511aac2c-90cd-11e8-9ee3-1486bcd07d46.png)

**Comment by jakubvano** [comment] 2018-07-27 08:01
@ZZHHAANNGG I suspect that your issue is caused by SwinjectStoryboard as well: as long as you have the SwinjectStoryboard framework linked to the project, and you are instantiating VCs from storyboard, SwinjectStoryboard methods will be called, and these "errors" will be printed.
