### ISSUE TITLE
Very slow checkouts when using Carthage

### ISSUE THREAD

**Issue by drekka** [Swinject/Swinject#206] opened 2016-12-12 01:38 UTC
Not sure where or what the issue is, but if I manually clone the repo using git, it checks out quite quickly. However if I add the repo as a Carthage dependency and do a Carthage update or bootstrap, it's really slow. Like as much as 5 - 10 minutes slow. Even worse if I add SwijectStoryboard.

**Comment by jakubvano** [comment] 2016-12-12 07:51
Hi @drekka,
is this issue specific to Swinject / SwinjectStoryboard, or are you observing it with other dependencies as well?

**Comment by drekka** [comment] 2016-12-12 10:18
It appears to be around Swinject and possibly SwinjectStoryboard. It's hard to tell. But the other dependencies checkout and build very fast in comparison. Will keep looking at this to see if I can figure out what the trigger might be. Have also logged this with the Carthage project in case they can shed some light on what might slow things down.

**Comment by yoichitgy** [comment] 2017-01-06 12:45
@drekka, did you find anything about this issue?

**Comment by drekka** [comment] 2017-01-08 02:36
Nothing further. I ran a test where I created a directory with nothing but a Cartfile with ObjectMapper and Swinject. 

Doing a manual clone of Swinject took about 10 secs. Using `carthage bootstrap --no-build` took about 40 seconds.

I then did a `carthage update --no-build`. ObjectMapper took about 2 seconds to update. Swinject took over 30 seconds.

**Comment by yoichitgy** [comment] 2017-01-08 06:41
Thanks @drekka for the update. If you still see the problem, we keep it open.

**Comment by yoichitgy** [comment] 2017-01-08 11:12
Related issue: https://github.com/Carthage/Carthage/issues/1636

**Comment by drekka** [comment] 2017-01-08 12:30
Yep. The problem is on-going. There are 3 of us here on this project and it's slow for all of us.

**Comment by yoichitgy** [comment] 2017-01-09 02:23
@drekka, you were asked to run commands combined with `&&` in the Carthage issue. Please answer there, because the issue is difficult to resolve without your help.

**Comment by yoichitgy** [comment] 2017-03-07 23:56
I'm going close this issue because it is tracked in Carthage project.

**Closed by yoichitgy** 2017-03-07 23:56 UTC
