### ISSUE TITLE
Type inference with multiple arguments

### ISSUE THREAD

**Issue by mpdifran** [Swinject/Swinject#153] opened 2016-09-17 23:17 UTC
Here's a fake representation of my setup (my code is too complicated to paste directly).

    extension NSFetchedResultsController: MDFFetchedResultsController { }

    class TableViewControllerAssembly: AssemblyType {

        func assemble(container: Container) {
            container.registerForStoryboard(TableViewController.self) { (r, c) in
                let controller = r.resolve(MDFFetchedResultsController.self)!

                // This line throws an error when unwrapping the optional.
                let dataSource = r.resolve(MDFDataSource.self, arguments: (c.tableview, controller))! 

                c.dataSource = dataSource
                c.tableView.dataSource = dataSource
            }
        }
    }

    class MDFConcreteDataSource: MDFDataSource {
        let tableView: UITableView
        let controller: MDFFetchedResultsController

        init(tableView: UITableView, controller: MDFFetchedResultsController) {
            self.tableView = tableView
            self.controller = controller
        }
    }

    class DataSourceAssembly: AssemblyType {

        func assemble(container: Container) {
            container.register(MDFDataSource.self) { r, tableView, fetchedResultsController in
                MDFConcreteDataSource(tableView: tableView, controller: fetchedResultsController)
            }
        }
    }

I believe the issue is Swinject doesn't find the registry due to how it determines the type of an object when using arguments. The registry is looking for a protocol (`MDFFetchedResultsController`), and I'm passing in a concrete implementation of the protocol (`NSFetchedResultsController `) as an argument.

I've also tried explicitly typing `controller` like so: `let controller: MDFFetchedResultsController = ...`.

Any thoughts on what's going on, or how I could work around this issue?

I'm using Swinject at this commit: `c598e7a`.

**Comment by yoichitgy** [comment] 2016-09-18 12:44
I think the problem is your registration of `MDFDataSource.self` with `registerForStoryboar` expects arguments though it does not support arguments. Reading #27 might be helpful for you.

**Comment by mpdifran** [comment] 2016-09-18 16:27
Ah sorry, that was a mistake when I was writing this up. I've updated to fix the mistake.

**Comment by yoichitgy** [comment] 2016-09-18 17:54
No worries. I think the naming of `registerForStoryboard` is confusing. I submitted an issue to rename the method: https://github.com/Swinject/SwinjectStoryboard/issues/21

**Comment by mpdifran** [comment] 2016-09-19 17:15
Just to be clear, this was a mistake when I was writing the fake example. My problem still persists with the above setup. Swinject can't find the correct registry with the given arguments.

**Comment by jakubvano** [comment] 2016-09-19 20:03
I suspect the problem is passing implicitly unwrapped optionals as arguments instead of wrapped values:
` (c.tableview, controller)` is of type `(UITableView!, MDFFetchedResultsController!)`, while your registration is with arguments of type `(UITableView, MDFFetchedResultsController)`

Explicit upcasting should fix the issue, i.e:
```
r.resolve(MDFDataSource.self, arguments: (c.tableview as UITableView, controller as MDFFetchedResultsController))
```

**Comment by mpdifran** [comment] 2016-09-20 01:43
Ah good call. I made the following change and it was able to resolve the dependency properly:

    let dataSource = r.resolve(MDFDataSource.self, arguments: (c.tableview as UITableView, controller))!

Upcasting the `controller` didn't seem to make a difference.

**Comment by jakubvano** [comment] 2016-09-20 08:00
For some reason I thought that implicitly unwrapping an optional returns value of type `ImplicitlyUnwrappedOptional` instead of wrapped type. Good to know that is not the case 😄 

I guess we can close this now.

**Closed by jakubvano** 2016-09-20 08:00 UTC
Labels: question

**Comment by yoichitgy** [comment] 2016-09-20 16:02
I think it's good to modify the documentation for `arguments` to explicitly specify types like 

```swift
container.register(AnimalType.self) { (_: ResolverType, name: String, running: Bool) in
    ...
}
```

and 

```swift
let name: String = "Lucky"
let running: Bool = true
container.resolve(AnimalType.self, arguments: name, running)!
```

to recommend typing the arguments explicitly. Swinject users can drop the explicit types by their own understandings.

https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#registration-with-arguments-in-a-di-container

**Comment by jakubvano** [comment] 2016-09-20 16:15
As this issue of not exactly matching types comes up quite often, maybe we could implement some runtime warning messages similar to [checkedResolved](https://github.com/Swinject/SwinjectAutoregistration/blob/master/Sources/AutoRegistration.swift#L682), which would somehow log that `resolve` failed, what arguments were given, and maybe some suggestion to what might be an problem..

Not sure about implementability yet, but something like
```
Resolving of MDFDataSource failed.
Name: -
Arguments: UITableView!, MDFFetchedResultsController

Found similar registration for MDFDataSource:
Name: -
Arguments: UITableView, MDFFetchedResultsController
```

**Comment by yoichitgy** [comment] 2016-09-22 09:58
@jakubvano, yes you are right. The Swifty way is important. I'll update the Remark section shortly. An example with optionals makes sense!
