### ISSUE TITLE
Use "inObjectScope" cause "Segmentation fault: 11"

### ISSUE THREAD

**Issue by d6u** [Swinject/Swinject#2] opened 2015-08-26 04:01 UTC
XCode 6.4, Swift 1.2

```swift
import UIKit
import Swinject

class Cat {
}

class ViewController: UIViewController {

    override func viewDidLoad() {
        let container = Container()
        container.register(Cat.self) { _ in Cat() }
            .inObjectScope(.Container)
    }
}
```

Calling `.inObjectScope(.Container)` will succeed only when you do typecasting like

```swift
(container.register(Cat.self) { _ in Cat() } as ServiceEntry<Cat>).inObjectScope(.Container)
```

I guess that's the bug of XCode?

**Comment by yoichitgy** [comment] 2015-08-26 04:42
Thank you for reporting the issue. I reproduced it and could not compile the file because of the segmentation fault. It looks a bug of Swift compiler with Xcode 6.4. If you set the returned value from `register` to a parameter and invoke `inObjectScope` on it, the compiler segmentation fault does not occur.

    let service = container.register(Cat.self) { _ in Cat() }
    service.inObjectScope(.Container)

Xcode 7 beta does not get the segmentation, and successfully finishes compiling.

**Comment by yoichitgy** [comment] 2015-08-26 04:46
**Workaround**

One of the followings can be a workaround:

- Cast the returned value to `ServiceEntry<T>` as @d6u said.
- Set the returned value from `register` to a parameter, then invoke `inObjectScope` on it as I said in the previous comment.
- Use Xcode 7 (beta).

**Comment by yoichitgy** [comment] 2015-08-26 04:51
I keep this issue open until Xcode 7 is officially released, then close it.

**Closed** 2015-09-15 15:19 UTC
Labels: bug, wontfix
